### ISSUE TITLE
Initial notes & comments

### ISSUE THREAD

**Issue by seanvree** [levic92/LCExtractor#1]
My environment:

Windows 10P x64 1703
Deluge: 1.3.15
Python:  2.7.13

First, GREAT WORK!!!

So a couple UI questions:

1 - So, IF extract in place is checked, then it doesn't use the specified "extract to" path?  Kinda confusing, does it extract to the specified folder, OR in place? 

2 - What exactly does sonarr/radarr support do?  There's no options to config a API call, so just wondering. 

So, tested a simple in place extraction, WITH the label auto move enabled-  and it worked! So that's dope!  (as you know, simple extraction is easy, but getting it to work with labels that auto-move after completion hasn't been mastered yet, until this! )

Gotta test with a sonarr/radarr manual grab,  Will report back. 

Great work man!

**Comment by levic92** [comment]
1. That is correct, it will override the specified folder and will extract to where the torrent is saved. I will add some notes to clarify this.

2. No API calls. I inspected the Sonarr/Radarr code and found what I believe is being used to determine when the torrent can be processed. So basically I toggle some attributes on the torrent to make sure it doesn't get processed by Sonarr/Radarr until it is done extracting.

**Comment by levic92** [comment]
I should also note that if you want Sonarr/Radarr support you will need to have that option checked as well as the extract in place option.

Let me know how your testing with Sonarr and Radarr goes.

**Comment by seanvree** [comment]
@levic92 

WOw man, worked. this is HUGE man!

One point - 

After sonarr/radarr imports the extracted file, I wonder how you could config to remove ( i.e MOVE the file instead of copying it)  But this wouldn't work on the sonarr/radarr side because it would then remove files that weren't RARed orginally, thus breaking your seeding. 

I also tested this by removing the torrent+data from the Deluge GUI, and sure enough, it left the original extracted file behind.  

Thoughts?

**Comment by levic92** [comment]
I haven't thought of a way to clean up after the files are imported by Sonarr/Radarr yet. I will need to take some time and see what I can come up with, but let me know if you have any ideas.

As far as when manually removing a torrent I could possibly use the TorrentRemovedEvent from Deluge.

**Comment by seanvree** [comment]
@levic92  - Yeah, the TorrentRemovedEvent sounds like the best/only option.

**Comment by seanvree** [comment]
@levic92  posted here:


https://forums.sonarr.tv/t/unrar-win-new-guide-to-auto-process-rar-torrents-via-sonarr-w-o-drone-factory-edit-01-sep-17/15381
