### ISSUE TITLE
Radarr clean-up script

### ISSUE THREAD

**Issue by justinglock40** [levic92/LCExtractor#13]
Can your provide more detail or a screenshot how this should be setup? Sonarr was straightforward this is not, at least to me.

<img width="529" alt="screenshot at jan 15 22-43-27" src="https://user-images.githubusercontent.com/23133649/34972219-ac33f506-fa45-11e7-8f5e-a9a63ca26299.png">

**Comment by levic92** [comment]
Something like this:
```"C:\...\lcextractor_cleanup.py" "radarr"```

**Comment by justinglock40** [comment]
Is it possible to mod the script to delete everything in the folder? I'm running sickbeard_mp4_automator script which changes the .mkv files to .mp4. So when the script goes to delete the folder it removes everything but that new file for obvious reasons.

**Comment by levic92** [comment]
You can modify the script for whatever works for you. I will be leaving it as is here because this is the function people generally need.
