### ISSUE TITLE
Need help / Py Newbie

### ISSUE THREAD

**Issue by talpazzo** [levic92/LCExtractor#15]
Dear Levic92, dear members of the Community,
I'm a newbie regarding python and so I don't understand some things. I hope you'll have the patience to help me understand how to configure everything correctly. Thank you in advance.
Sonarr: 2.0.0.5085
Radarr: 0.2.0.910
Deluge: 1.3.15
Windows: 10 pro@64 

1) LCExtractor-0.6.2-py2.7.egg
a.  General settings
Every time I close and re-open Deluge I loose all the settings. 
I installed a clean version of Deluge, deleted every languages except english to force to use EN, started as an administrator, reinstalled various times,... nothing to do :( 
It always revert back to my user folder and the checkbox does not stay checked. 

2) lcextractor_cleanup.py 
a. json api endpoint for deluge web service
I opened the script to see what is the deluge_url: http://127.0.0.1:8112/json (default)
I tried to click the link to see if it's correct, I got: "This page isn’t working If the problem continues, contact the site owner. HTTP ERROR 405"
If I go to http://127.0.0.1:8112/ I got the web interface.
It is correct to see a 405 error from the browser?
b. Sonarr Setup
Path - Full path to your python executable
where do I find this?
c. Radarr Setup
- Path - Full path to your python executable 
where do I find this?
- Arguments - Full path to lcextractor_cleanup.py AND "radarr"
--> J:\Torrents\script\lcextractor_cleanup.py AND "radarr"
is right this way?

As I said I don't understand much of python and scripts.py. I hope you can point me in the right direction so I can use too this wonderful script. 
Thank you for your time and your patience. talpazzo

**Comment by levic92** [comment]
1. Use the web UI and not the windows GUI. I could not get the windows GUI to reliably keep the settings but the Web UI works fine.

2. a. that is probably fine
b. you will need to find where python is installed... Probably something like "C:\Program Files\Python36\python.exe"
c. radar arguments would be:
"J:\Torrents\script\lcextractor_cleanup.py" "radarr"
