### ISSUE TITLE
Sonarr and Radarr

### ISSUE THREAD

**Issue by justinglock40** [levic92/LCExtractor#16]
What would be the best way to get this plugin setup if I’m running deluge for VPN and Sonarr and Radarr on two different systems?

**Comment by levic92** [comment]
The plugin doesn't have anything to do with Sonarr or Radarr so if you just install it it will work fine.

If you are talking about the cleanup script then just make sure the parameters are set correctly. The fact that they are on 2 systems wont matter.

**Comment by justinglock40** [comment]
I tried that. But it doesn’t seem to be executing as the files don’t get processed
  

  
  

  
  
>

**Comment by justinglock40** [comment]
So I installed the .egg manual using the Web GUI that's connected to my deluged running on Ubuntu, but the files never get extracted. Any idea why it doesn't seem to be getting executed?
