### ISSUE TITLE
How to handle releases with subs in rar? Only subs get extracted. Movie file isn't.

### ISSUE THREAD

**Issue by luchtgitaar** [levic92/LCExtractor#19]
First time user. TV Series are working perfect! However when downloading movie releases (with a separate Subs directory, in that directory there is a .subs.rar file) it is not working as expected. Tested with multiple releases.

Maybe this is a configuration setting/issue, but at the moment only the subs.rar is extracted and the rar containing the .mkv is left intact.

![image](https://user-images.githubusercontent.com/38834802/40424205-3256a0e4-5e95-11e8-86f9-ba350637955c.png)

![image](https://user-images.githubusercontent.com/38834802/40424352-9def2b78-5e95-11e8-92ad-f316b8499021.png)

**Comment by luchtgitaar** [comment]
Apparently this is a TL specific way of uploading movies. I think I need a couple lines of code for the plugin to ignore the /subs/ folder, or for Deluge not download the /subs/ folder at all, but my Python skills are lacking.

Any help is much appreciated.

**Comment by Or1j1n** [comment]
+1

**Comment by warfighter8** [comment]
+1

**Comment by fcruz2489** [comment]
+1

**Comment by levic92** [comment]
See issue #11 I will track it in there
