### ISSUE TITLE
Append label to path

### ISSUE THREAD

**Issue by jkaberg** [levic92/LCExtractor#2]
It would be nice if one could append label (if it's set) to path when extracting, eg.

/path/to/dir/**label**/

So when one has enabled extract to subfolder it could look like this

/path/to/dir/**label**/**torrent name**

This would be great for sorting stuff

**Comment by levic92** [comment]
I will consider this option if enough people requested it.

Currently I have a different "Move completed to" path set for each label, and then I use the extract in place option so essentially they are being organized like that.

**Comment by seanvree** [comment]
@jkaberg  - 

If you already have the label appended with sorting enabled, there would be no need for this, as this plugin should execute AFTER it's moved to the proper DIR, i.e movies, TV, music, etc
