### ISSUE TITLE
Using lcextractor_cleanup.py in combination with sickbeard_mp4_automator script

### ISSUE THREAD

**Issue by mcleodd10** [levic92/LCExtractor#22]
LCExtractor has been working well for processing however I've been using it in combination with the aforementioned mp4 automator script ( https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/README.md ) and currently, once the file is exctacted (usually an mkv) Sonarr picks up the file and copies it to the destination folder, then the automator script is called by Sonarr and the mkv is converted to an mp4, the copy of the mkv in the destination folder is then deleted. Only trouble comes is when lcextractor_cleanup.py is called it can't find the imported file (this appears in the log) as the remaining converted mp4 file doesn't match the original mkv in the source directory.

I don't know a lick of Python (or any other language for that matter) and I've looked through the script to see if I can understand what it's doing, but I guess the check is happening at `if os.path.exists(destpath):` though I don't know if setting destpath or a new variable to  sonarr_deletedpaths or  sonarr_deletedrelativepaths would accomplish what I'm looking to do, or whether those environment variables would even contain the path to the original mkv file. Any ideas that might push me in the right direction?

Cheers!

**Comment by seffyroff** [comment]
You might want to try turning off some of the LCExtractor support for moving the extracted movie, and let MP4 Extractor do it instead perhaps?  Haven't tried that myself yet, let me know if it helps!

**Comment by levic92** [comment]
I'm not sure what you are trying to accomplish. The purpose of lcextractor_cleanup is to delete the extracted video file since deluge wont clean this up when deleting the torrent.

If you are saying you want the newly created mp4 to be deleted instead you can try 1 of the following things:

1. You can remove the check ```os.path.exists(destpath)```

2. You can modify the check for destpath to check for existence  ```destpath``` or ```destpath``` with the extension replaced with mp4

**Comment by mcleodd10** [comment]
@levic92 Guess I overcomplicated my explanation; basically I want the extracted video file (mkv in same directory) to be deleted, like the cleanup script should do normally. The problem is that the cleanup script can't find it if the mp4automator script is also in use.

My guess as to why this is happening is that when Sonarr imports the file, it's importing the newly created mp4; and when the cleanup script check to see which item was imported, it's seeing this new mp4, and not the original mkv that I would like to be deleted; hence why it's returning "Could not find imported file" in the log.

**Comment by evilmanimani** [comment]
@levic92 hey, sorry I closed this by accident.
