### ISSUE TITLE
Deluge 2.0 support 

### ISSUE THREAD

**Issue by ngodber** [levic92/LCExtractor#28]
Hi

Now that Deluge has iterated to 2.0 and python 3 are there any plans to migrate this awesome plugin?

Cheers,
Neil

**Comment by keklol123** [comment]
Would also love this..

**Comment by syrigx** [comment]
We really miss this plugin from deluge 2, especially for the sonarr/radarr support

**Comment by ngodber** [comment]
Unforuntaly it looks like this plugin is no longer developed. Once deluge 2.0 develops support for windows I'll see if i can't migrate this plugin. Had a quick look and its just to much of a PITA until windows support has been rolled in.

**Comment by trymbill** [comment]
I just found a fork of this repo that seems to work fine with Deluge 2.0 on Python 3.7: https://github.com/Chris-V/LCExtractor

**Comment by mcrommert** [comment]
> I just found a fork of this repo that seems to work fine with Deluge 2.0 on Python 3.7: https://github.com/Chris-V/LCExtractor

So i built the egg from the 3.0 version and its still not showing up - share your file?

**Comment by nameproof** [comment]
> 
> 
> > I just found a fork of this repo that seems to work fine with Deluge 2.0 on Python 3.7: https://github.com/Chris-V/LCExtractor
> 
> So i built the egg from the 3.0 version and its still not showing up - share your file?

Build it with python3

**Comment by Enf0** [comment]
> > I just found a fork of this repo that seems to work fine with Deluge 2.0 on Python 3.7: https://github.com/Chris-V/LCExtractor
> 
> So i built the egg from the 3.0 version and its still not showing up - share your file?

Same here. I build it with Python 3.6 and place it in the plugins folder, but it doesn't show up in Deluge.

Could anyone who got it working post their .egg here, please?

EDIT: Nevermind. I built with Python 3.7 instead of Python 3.6.7 and it seems to have worked.

**Comment by trymbill** [comment]
> > > I just found a fork of this repo that seems to work fine with Deluge 2.0 on Python 3.7: https://github.com/Chris-V/LCExtractor
> > 
> > 
> > So i built the egg from the 3.0 version and its still not showing up - share your file?
> 
> Same here. I build it with Python 3.6 and place it in the plugins folder, but it doesn't show up in Deluge.
> 
> Could anyone who got it working post their .egg here, please?
> 
> EDIT: Nevermind. I built with Python 3.7 instead of Python 3.6.7 and it seems to have worked.

Came here to suggest using 3.7 instead of 3.6 👍

**Comment by stealthgyro** [comment]
I've had no luck with this. Building it is fine, but trying to install this thing either manually in the plugins folder, web interface, or thin client... None seem to work.

**Comment by schullq** [comment]
Still struggling with the same issue here. Tried the the fork which is supposed to work with python 3.7 but it's not for me. The plug-in is not showing up in the plug-in lists. Also tried to compile using python3.8, but not working as well. I am using Deluge 2.0.3-2201906121747ubuntu18.04.1-ls47 docker version.

**Comment by ngosang** [comment]
I'm using https://github.com/Chris-V/LCExtractor in LinuxServer Deluge 2.0.3 (Docker image)
I recommend you to compile from source code using Python 3.6. For those who can't:
1. Download this file [PVRExtractor-0.7.0.1-py3.6.zip](https://github.com/levic92/LCExtractor/files/5824408/PVRExtractor-0.7.0.1-py3.6.zip)
2. Rename the file to `PVRExtractor-0.7.0.1-py3.6.egg` (I changed the extension to ZIP because EGG extension is not allowed in GitHub).
3. Place the file in the `config/plugins` folder
4. Restart Deluge. You will see the plugin in the Web UI. You can enable it in Preferences => Plugins
