### ISSUE TITLE
Extracted file remains after import

### ISSUE THREAD

**Issue by seanvree** [levic92/LCExtractor#5]
@levic92  

Yo brotha. 

Have you done any work on this lately?  

Trying to figure out how to remove the leftover extracted file once sonarr/radarr imports it.  

Any ideas?

**Comment by levic92** [comment]
Not yet, I haven't had much time for this lately. It's not a simple problem to solve. I have a couple ideas but will need some time to experiment

**Comment by seanvree** [comment]
@levic92 

Yeah, all good brotha.  LMK if you want some help.

**Comment by danpowell88** [comment]
shouldn't sonarr/radarr remove the file if you have the correct options setup in the settings

**Comment by seanvree** [comment]
@danpowell88  good question.  However, NO, sonarr/radarr aren't designed to deal with extracted files. which is why we are in the mess.  Sonarr/ Radarr don't know if the "grabbed" release was a RARed or not.  It just looks for a media file in the release once the downloader has finished.  If the downloader reports complete, but there's no media file (AKA RARed) then you get the "no media files found" error in Sonarr/Radarr.  

There's a reason @levic92  designed this, and it boggles my mind how people keep saying "there's no issue, many plug-ins do this...or radarr sonarr do this".  NO they don't, not properly nor automated.     People keep missing the fact that "all the other extractors" out there can't extract BASED on labels, and sonarr/radarr don't know if the original release needed to be extracted or not.  

Now, you would be correct IF all your files were from .RAR OOOORRR all your files were from non-rar, **But, the problem is that if you choose to remove after importing, then that means that all your releases that didn't need to be extracted would be removed and break your seeding.**  

I've been using Sonarr/Radarr since their launch...and I've actually worked with the DEVs a bit.   Great kit, great dudes.  However, it's still pretty amazing that the ONE thing CouchPotato did well, was exactly this.

**Comment by danpowell88** [comment]
ah I see, im considering switching from qbitorrent due to some weird issues where I think sonarr/radarr is picking the files up before they are completed, or perhaps qbitorrent is somehow borking the unrar (could also be my script).

In any case I kill all my torrents as soon as their done so I don't think it would be an issue here

**Comment by seanvree** [comment]
@danpowell88 lol. def not.  

This is for dudes who use Deluge on Windows with private trackers that occasionally server up .RAR releases.  If you don't fit that bill, this isn't for you brotha.

**Comment by QuickShotx** [comment]
@danpowell88 This solved that problem for me.   I was using deluge + extractnow and sonarr would pull in 50% extracted tv show.... So it'd just crash halfway through playback.   If I just recopied the file it'd work, since extractnow would continue to finish the file.

@seanvree   Windows isn't required, just Deluge.

**Comment by seanvree** [comment]
@QuickShotx I know windows is NOT required, I prob could have used better verbiage.   But from what I know, there are a few UNIX-based scripts that DO solve this problem if using deluge on linux.  I'm  windows guy, so I can't confirm, but most of the dudes I've seen with this issue have been from Windows users. 

I was also using the extractnow method for a long time as well. This is the most promising tool that's properly addressed the issue.

**Comment by levic92** [comment]
I have a python script that I'm testing right now to automatically clean up extracted files (at least extracted files that are imported by sonarr or radarr). The script will be triggered as a custom script at "On Download" and "On Update" in sonarr and radarr. I will upload it here once I have had some more time to test it.

**Comment by seanvree** [comment]
wurd, looking forward to it @levic92 .

**Comment by levic92** [comment]
Give this a try [https://github.com/levic92/LCExtractor/tree/master/extras](url)

**Comment by seanvree** [comment]
@levic92  Running some tests now brotha!

**Comment by seanvree** [comment]
@levic92 Looks good brotha!   

I keep seeing an error in the log from Deluge, but it is extracting and deleting the leftover files after Sonarr imports it, so it looks to be working. Not sure why that error is popping up. 

```
Nov 24 20:12:06 DelugeVSB deluge.log: [ERROR   ] 20:12:04 core:204 EXTRACTOR: Extract failed: C:\Media\Plexdownloads\tv\torrents\The.Last.Man.on.Earth.S03E13.1080p.HDTV.x264-SERIOUSLY\the.last.man.on.earth.s03e13.1080p.hdtv.x264-seriously.rar (ef0987776a9d3005f5c3b2989bd1f9014149fdcb) ERROR: Can not delete output file : The process cannot access the file because it is being used by another process. : .\the.last.man.on.earth.s03e13.1080p.hdtv.x264-seriously.mkv 
Nov 24 20:12:20 LCExtractor lcextractor_cleanup.log: 11/24/2017 20:12:19 - INFO - [The.Last.Man.on.Earth.S03E13.1080p.HDTV.x264-SERIOUSLY] Starting lcextractor_cleanup in mode: sonarr
Nov 24 20:12:22 LCExtractor lcextractor_cleanup.log: 11/24/2017 20:12:21 - INFO - [The.Last.Man.on.Earth.S03E13.1080p.HDTV.x264-SERIOUSLY] Delete
```


Good work man, Seriously. Game changer.
