### ISSUE TITLE
Settings clarification

### ISSUE THREAD

**Issue by danpowell88** [levic92/LCExtractor#6]
Are you able to explain some of the settings?

I have the following config

```
{
  "file": 1, 
  "format": 1
}{
  "use_name_folder": false, 
  "sonarr_radarr_support": true, 
  "extract_path": "/data/incomplete", 
  "in_place_extraction": true
}
```

completed files are moved to /data/completed, however when the plugin runs its extracting the file to the root of the directory /data/completed.

Have in place extraction set to true I thought it would extract to whatever the location of the torrent data is in (if there is one).

Am I missing something here, I guess I could just use the folder name but that might be off if the torrent is just single file which happens from time to time.

**Comment by levic92** [comment]
**sonarr_radarr_support**: toggles attributes so the torrent isn't imported until the extraction is done

**extract_path**: is the default destination directory to extract files to

**in_place_extraction**: overrides extract_path destination directory and instead uses the "save_path" of the torrent in deluge

**use_name_folder**: will append another directory to the extraction path that has the same name as the torrent. The script checks to make sure that this path doesn't exist or that it is a directory, this covers the case where the torrent is just a single file


You will want use_name_folder set to true

**Comment by danpowell88** [comment]
Interesting, I'm guessing save_path is the root of the folder (in my case /data/complete for a torrent in /data/complete/foo.s01e01.hdtv.xvid-lol).

Is there a deluge variable that already gives us the actual contents root folder without having to calculate it ourself?

**Comment by levic92** [comment]
Yes that is correct.

Here are more details on what is available from Deluge.

I am happy with the way it works in combination with the use_name_folder option and have had no issues with it so far. But this is making me think I should automatically set this option to true if you enable sonarr_radarr_support

**Comment by danpowell88** [comment]
Seems like save_path is deprecated as well

https://github.com/deluge-torrent/deluge/blob/0ba87b424c6781beefa450696042bf4e9abeb64b/deluge/core/torrent.py#L1019

**Comment by levic92** [comment]
Yes I know but I am on an older version of Deluge
