### ISSUE TITLE
Error:  "This file was not in an archive"

### ISSUE THREAD

**Issue by seanvree** [levic92/LCExtractor#7]
Yo @levic92  been seeing this error a few times. Has been working but I would say I get this about 25% of the time.    Not sure what's causing it.  It extracts fine, and the script runs,  but doesn't remove it. with the errors below. 

```
Dec 02 21:35:14 LCExtractor lcextractor_cleanup.log:  12/02/2017 21:35:13 - INFO - [Outlander.S03E12.WEB.H264-STRiFE] Starting lcextractor_cleanup in mode: sonarr
Dec 02 21:35:17 LCExtractor lcextractor_cleanup.log:  12/02/2017 21:35:16 - INFO - [Outlander.S03E12.WEB.H264-STRiFE] This file was not in an archive
```

![image](https://user-images.githubusercontent.com/8906637/33524430-3340fbca-d7d2-11e7-9102-5bef7355592a.png)

**Comment by levic92** [comment]
What files are in the sample directory

**Comment by seanvree** [comment]
@levic92  that would be the sample.mkv that is was in the torrent data un-archived.

**Comment by levic92** [comment]
Add this to line 58 (after filename is defined)
```py
xprint("deluge_url: " + (deluge_url or "") + ", download_id: " + (download_id or "") + ", sourcepath: " + (sourcepath or "") + ", destpath: " + (destpath or "") + ", download_name: " + (download_name or "") + ", filename: " + (filename or ""))
```
And add this to line 108 (before torrent is defined)
```py
xprint(results)
```

That message isn't an error, it means that the filename that was imported was also in the deluge file list. So I need to know what file sonarr is importing and then also what is contained in the files list from deluge.

Trigger a download of the same torrent through sonarr again and report back the logs.

**Comment by seanvree** [comment]
will do @levic92  I'll report back.

**Comment by seanvree** [comment]
@levic92  I must not be editing the code right, this is the error I'm getting now:

```
17-12-5 08:31:55.3|Error|python.exe|IndentationError: unexpected indent 
17-12-5 08:31:55.3|Error|python.exe| ^ 
17-12-5 08:31:55.3|Error|python.exe| auth = '{"method": "auth.login", "params": ["' + deluge_password + '"], "id": 1}' 
17-12-5 08:31:55.3|Error|python.exe| File "C:\LCExtractor\extras\lcextractor_cleanup.py", line 59
```

Here is what that block of code looks like:

```
if deluge_url and sourcepath and destpath and (download_id or download_name):
    filename = ntpath.basename(sourcepath)
        xprint("deluge_url: " + (deluge_url or "") + ", download_id: " + (download_id or "") + ", sourcepath: " + (sourcepath or "") + ", destpath: " + (destpath or "") + ", download_name: " + (download_name or "") + ", filename: " + (filename or ""))
    auth = '{"method": "auth.login", "params": ["' + deluge_password + '"], "id": 1}'
    auth_params = 
```

**Comment by levic92** [comment]
Python relies on the tabs so just make sure those are correct. Check to see if the file is using spaces for tabs if everything looks aligned

**Comment by seanvree** [comment]
@levic92  good to know. Seems to be working now.  I think it's just random file locks. 

Thanks brotha. 

Also, been blasting your tool here:  https://forums.sonarr.tv/t/guide-automatically-process-rar-releases-in-sonarr-radarr-while-using-usenet-and-torrents-on-a-windows-environment/13743/20

Hope that's OK.

**Comment by levic92** [comment]
@seanvree glad to hear it's working. In the future if there are any problems those log lines would be the place to start to get more details to help determine why.

That's definitely OK, the more people who can use it the better. Thanks!
