### ISSUE TITLE
Can't get cleanup working.

### ISSUE THREAD

**Issue by DemonCow5761** [levic92/LCExtractor#8]
I'm on windows 10 and put in these pointing at my python.exe and the lcextactor_cleanup.py but it doesn't appear to do anything no log file created or anything.

Path - C:\Python27\python.exe
Arguments - E:\LCExtractor Cleanup\lcextractor_cleanup.py

On Download - yes
On Upgrade - yes
On Rename - no
On Grab - no

If I double click the lcextractor_cleanup.py I get this in the log

12/03/2017 21:19:07 - INFO - [] Starting lcextractor_cleanup in mode: sonarr

12/03/2017 21:19:07 - ERROR - [] Missing required variables

12/03/2017 21:19:07 - ERROR - [] deluge_url: http://127.0.0.1:8112/json, download_id: , sourcepath: , destpath: , download_name: 

Am I doing something obviously wrong here?  I get to deluge from localhost:8112 and password deluge so I assume the json/password are fine.

**Comment by levic92** [comment]
Double clicking the script will do nothing because it needs the variables from sonarr. If you didn't see the log file created that means sonarr wasn't triggering it. You should look in the sonarr log files to see why it isn't running the script.

**Comment by DemonCow5761** [comment]
Oh thanks I guess it was my argument having the space in the folder name it was trying to run just "e:\lcextractor" instead of "E:\LCExtractor Cleanup\lcextractor_cleanup.py" I just took the space out of the folder, hopefully it'll work next rar file.

Thanks, knew it had to be something stupid.

**Comment by seanvree** [comment]
@DemonCow5761  were you able to fix this issue?  I have it running fine for Sonarr, but just set it up for Radarr, and I'm getting the same error as you: "Missing required variables ".  It extracts fine, it just won't deleted the extracted file. 


Radarr settings:
path:  `C:\Python36\python.exe`
Arguments: `C:\LCExtractor\extras\lcextractor_cleanup.py`

![image](https://user-images.githubusercontent.com/8906637/43063832-52d9d53e-8e1a-11e8-950b-65694d3b2ba6.png)


RADARR Log:
```
Line 0 : 18-7-23 00:39:47.7|Error|python.exe|[] deluge_url: https://seanvree.com:8114/json, download_id: , sourcepath: , destpath: , download_name: 
Line 1 : 18-7-23 00:39:47.7|Error|python.exe|[] Missing required variables 
```

LCExtractor_Cleanup_log:
```
Line 0 : 
Line 1 : 07/23/2018 00:39:47 - ERROR - [] deluge_url: https://seanvree.com:8114/json, download_id: , sourcepath: , destpath: , download_name: 
Line 2 : 
Line 3 : 07/23/2018 00:39:47 - ERROR - [] Missing required variables 
Line 4 : 
```



@levic92  you still developing this?

Thanks!

**Comment by levic92** [comment]
You are missing an argument. It should be:

"C:\...\lcextractor_cleanup.py" "radarr"

Same as was stated in issue #13

**Comment by seanvree** [comment]
@levic92  thanks brotha. Out of curiosity, does Sonarr require that argument as well? I don't have that and it has been working since you launched this project.

**Comment by mcleodd10** [comment]
I was having a peek at the script and it looks like sonarr is the default mode, it'll only run in radarr mode if the argument is passed.

**Comment by seanvree** [comment]
That makes sense my man.

Thanks.
