### ISSUE TITLE
Feature Request - Extract based on 'label' or 'on-completion path'

### ISSUE THREAD

**Issue by ghost** [levic92/LCExtractor#9]
Love this plugin so far and I'm a daily user of it, really glad you took it upon yourself to solve this problem that a lot of us have! I only have one small annoyance with it.

The plugin cannot differentiate between the different torrent groupings (labels) so everything I download gets extracted. Personally, I have 2-3 different labels that I would prefer get auto-extracted, and leave everything else alone.

I don't know if you're able to parse torrent labels from deluge and add some sort of "_if label=INSERT_LABEL then extract_" kind of deal, but that would certainly be great for my use case, and I'm sure a lot of other people would like such a feature as well.

If checking torrent labels isn't an option, perhaps verify the move-on completion paths of the torrent-files before extraction (only things located under a certain folder gets extracted, everything else gets left alone).

That being said, love the work and really appreciate it!

**Comment by levic92** [comment]
This is something I can look at next time I do some work on the Plugin. No ETA at the moment but it should be possible.

**Comment by itslukej** [comment]
+1

**Comment by netvyper** [comment]
Would really love to see this one added; we have different labels & paths for TV/Movies/Stuff...
